name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main, master]

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    name: Conventional PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
